-- CREATE DATABASE AND USER, GIVING READ PERMISSION
CREATE DATABASE 'hbtn_0d_2';
CREATE USER IF NOT EXISTS 'user_0d_2' IDENTIFIED BY 'user_0d_2_pwd';
GRANT SELECT ON 'htbn_0d_2'@'localhost' TO 'user_0d_2'@'localhost';